[package]
name = "corelink-simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
corelink-core = { path = "../core" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }